### PR TITLE
Add fil memory profiler

### PR DESCRIPTION
**Pull request by petrem**

### CODE REVIEW

**Comment by JackMcKew** [comment]
Thank you so much!

/check-pr

**Comment by JackMcKew** [comment]
Some checks failled :(, check Github Actions for more details.

**Comment by JackMcKew** [comment]
Could you please add the following into the word list to exclude if they are spelled correctly:

- filprofiler
- Fil
- profiler
- Fil
- profiler
- APIs
- Fil

**Comment by petrem** [comment]
Yes, will do. A good opportunity to get actions/workflows flowing.

**Comment by JackMcKew** [comment]
Thank you! 

/check-pr

**Comment by JackMcKew** [comment]
👋 All checks passed!

**Pull request merged**
